name: Build Windows EXE

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller PyPDF2

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --add-data "priority_config.json;." pdf_manager_gui.py

      - name: Zip the .exe
        run: |
          Compress-Archive -Path dist\pdf_manager_gui.exe -DestinationPath pdf_manager2_windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-manager-windows
          path: pdf_manager2_windows.zip
